### ISSUE TITLE
The debloated version is larger

### ISSUE THREAD

**Issue by ppashakhanloo** [cxreet/razor#1]
Thanks for your interesting tool!

I followed the steps in README files to set up and run Razor. However, I noticed that the debloated bzip binary is larger than the original binary.
Also, as noted in the instructions, I follow the steps to run like this: 1->2->3->4->5->3->4->5.
But I still get the segmentation faults.

I am running Razor on a Ubuntu 18.04 VM. Are there any OS-specific settings or steps that I have missed?

Thanks.

**Comment by huhong789** [comment]
Thanks for the feedback, Pardis. Please see my answers as follows:

1. The binary size is larger, as we conservatively keep the old code section in the binary. Since we have make it non-executable, the old code is generally believed to be harmless.
2. I have fixed a bug in our code, please try the bzip2 debloating again.

Any future comments are welcomed!

**Comment by huhong789** [comment]
It seems Pardis accepts my answer. let me close the issue.
